services:
  - type: web
    name: flask-app
    env: python
    build_command: |
      pip install -r requirements.txt
      # Ensure all files are included in the build
      cp -r saved_models /opt/render/project/src/
    start_command: gunicorn -w 4 -b 0.0.0.0:${PORT} app:app
    plan: free
